#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S3,     sonarFront,     sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnRight();
void turnLeft();
void goForward();
void goForward(int distance); // distance in cm
void wallTrack();
void leftUturn();

int foundCheese();

task main()
{
	while(!foundCheese())		//while robot has not found cheese
	{
		if (SensorValue(sonarFront)
	}
}

void turnRight(){
	nSyncedMotors = synchBA;	//Synch two motors. B is the master motor, and A is the slave motor.
	nSyncedTurnRatio = -100;	//Motor A will recieve the opposite of what motor B recieves
	motor[motorB] = 30;
	wait1Msec(1000);
}

void turnLeft(){
	nSyncedMotors = synchAB;	//Synch two motors. A is the master motor, and B is the slave motor.
	nSyncedTurnRatio = -100;		//Motor B will recieve the opposite of what motor A recieves
	motor[motorA] = 30;
	wait1Msec(1000);
}

void leftUturn(){
	goForward(20);
	turnLeft();
	goForward(10);
	turnLeft();
	goForward(20);
}

void goForward(){
	nSyncedMotors = synchAB;	//Synch two motors. A is the master motor, and B is the slave motor.
	nSyncedTurnRatio = 100;		//Motor B will recieve 100% of what motor A recieves
	motor[motorA] = 30;
}

void goForward(int distance){
	nSyncedMotors = synchAB;	//Synch two motors. A is the master motor, and B is the slave motor.
	nSyncedTurnRatio = 100;		//Motor B will recieve 100% of what motor A recieves

	int diameter = 5;		//cm -- Change this value if your wheel size is a different size
	float degrees = distance/(diameter*PI)*360;

	nMotorEncoderTarget[motorA] = (int)degrees;		//Rotates motor A for a specified amount of degrees
	nMotorEncoderTarget[motorB] = (int)degrees;		//Rotates motor B for a specified amount of degrees

	motor[motorA] = 50;
	motor[motorB] = 50;
	wait1Msec(2000);
}

void wallTrack(){
	while(SensorValue(sonar) < 15)	//while moving towards the wall (sonar placed on the left side)
	{
		//move to the right
		nSyncedMotors = synchAB;	//Synch two motors. A is the master motor, and B is the slave motor.
		nSyncedTurnRatio = 70;		//Motor B will recieve 70% of what motor A recieves
		motor[motorA] = 30;
	}
	while(SensorValue(sonar) >= 15)	//while moving away from the wall (sonar placed on the right side)
	{
		//move to the left
		nSyncedMotors = synchBA;	//Synch two motors. B is the master motor, and A is the slave motor.
		nSyncedTurnRatio = 70;		//Motor A will recieve 70% of what motor B recieves
		motor[motorB] = 30;
	}
}

int foundCheese(){
	if (SensorValue(light) > 30)
		return 1;
	return 0;
}
