#pragma config(Sensor, S1,     touch1,         sensorTouch)
#pragma config(Sensor, S2,     sonar1,         sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	  /*motor[motorA] = 30;
		motor[motorB] = 0;
		wait1Msec(3000);
		
		motor[motorA] = 20;
		motor[motorB] = 20;
		wait1Msec(2000);*/
		
		while (SensorValue(touch1) == 0)
		{
			motor[motorA] = -50;
			motor[motorB] = -50;
		}
	
		motor[motorA] = 50;
		motor[motorB] = 50;
		wait1Msec(1000);
		
		motor[motorA] = 80;
		motor[motorB] = -80;
		wait1Msec(800);
	
		motor[motorA] = 50;
		motor[motorB] = 50;
		wait1Msec(3000);
}
